### PR TITLE
Blocknative modal customization

### PR DESCRIPTION
**Pull request by MusabShakeel576**
Added Blocknative's modal customization.

### CODE REVIEW

**Comment by MayankMittal1** [comment]
@MusabShakeel576 
image
can you change these text colours accordingly? they are not visible clearly

**Comment by MusabShakeel576** [comment]
@MayankMittal1 updated account center and action button text colors.

**Comment by MayankMittal1** [comment]
@MusabShakeel576 
image
is it possible to add border to this add account menu?

**Comment by MusabShakeel576** [comment]
@MayankMittal1 yeah. Added border in account center menu.

**Comment by MayankMittal1** [comment]
LGTM, merging

**Pull request merged**
