### PR TITLE
Update node attributes

### PR DESCRIPTION
**Pull request by fuseprime**
1)Update node 0x_2353 name and logo to BlockTelos
2)Add logo to GMCapital
3)Remove website from AmpGang

### CODE REVIEW

**Comment by fuseprime** [comment]
Changed to nodes as per the description. Image files added and json updated.

**Review by maorstamati — COMMENTED** [review]
@fuseprime changes look good, are those your nodes?

**Comment by fuseprime** [comment]
yes, they are nodes I manage

**Review by maorstamati — APPROVED** [review]
Approved and merging 👍🏻

**Pull request merged**
